[mypy]
plugins = pydantic.mypy

files = src/glone
python_version = 3.10

allow_redefinition_new = True
check_untyped_defs = True
disallow_any_generics = True
disallow_any_unimported = True
disallow_incomplete_defs = True
disallow_subclassing_any = True
disallow_untyped_calls = True
disallow_untyped_decorators = True
disallow_untyped_defs = True
error_summary = True
exclude_gitignore = True
extra_checks = True
follow_imports = normal
local_partial_types = True
no_implicit_reexport = True
pretty = True
show_column_numbers = True
show_error_context = True
strict_bytes = True
strict_equality = True
strict_equality_for_none = True
warn_incomplete_stub = True
warn_no_return = True
warn_redundant_casts = True
warn_return_any = True
warn_unreachable = True
warn_unused_ignores = True

enable_error_code =
    deprecated,
    exhaustive-match,
    explicit-override,
    ignore-without-code,
    mutable-override,
    possibly-undefined,
    redundant-expr,
    redundant-self,
    truthy-bool,
    truthy-iterable,
    unimported-reveal,
    unused-awaitable

incremental = True
sqlite_cache = True
# "The warn_unused_configs flag may be useful to debug misspelled section names.":
# - https://github.com/python/mypy/blob/v1.20.1/docs/source/config_file.rst#config-file-format
# - https://github.com/python/mypy/blob/v1.20.1/docs/source/config_file.rst#miscellaneous
# incremental = False
# warn_unused_configs = True

[pydantic-mypy]
init_forbid_extra = True
init_typed = True
warn_required_dynamic_aliases = True
